name: Show Me the S3cr3tz
# Controls when the workflow will run
on:
  workflow_dispatch:
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        KEY: ${{ secrets.AZURE_KEY }}
        HOST: ${{ secrets.AZURE_HOST }}
      run: |
        echo $KEY >> secrets.txt
        echo $HOST >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
